### ISSUE TITLE
Type error when changing password

### ISSUE THREAD

**Issue by shahar3000** [wheelybird/ldap-user-manager#159]
Hey,
Sometimes when I try to change user password, I get this type error:
```
Fatal error: Uncaught TypeError: str_replace(): Argument #2 ($replace) must be of type string when argument #1 ($search) is a string in /opt/ldap_user_manager/includes/mail_functions.inc.php:33 Stack trace: #0 /opt/ldap_user_manager/includes/mail_functions.inc.php(33): str_replace('{first_name}', Array, '\xD7\xA9\xD7\x9C\xD7\x95\xD7\x9D, \xD7\xA0\xD7\xA4\xD7...') #1 /opt/ldap_user_manager/account_manager/show_user.php(187): parse_mail_text('\xD7\xA9\xD7\x9C\xD7\x95\xD7\x9D, \xD7\xA0\xD7\xA4\xD7...', 'Rank-yin-openin...', 'sh12', Array, Array) #2 {main} thrown in /opt/ldap_user_manager/includes/mail_functions.inc.php on line 33
```
I am using version v1.8

**Comment by wheelybird** [comment]
This is fixed and pushed to `wheelybird/ldap-user-manager:v1.8` and `wheelybird/ldap-user-manager:latest`.
